name: Agent – apply file blocks from issue comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  apply:
    # Запуск только если комментарий содержит /apply
    if: ${{ contains(github.event.comment.body, '/apply') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse file blocks and write files
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body || "";
            const re = /```file=([^\n]+)\n([\s\S]*?)```/g;
            const fs = require('fs');
            const path = require('path');
            const files = [];
            let m;
            while ((m = re.exec(body)) !== null) {
              const p = m[1].trim();
              const content = m[2];
              const dir = path.dirname(p);
              if (dir && dir !== '.') fs.mkdirSync(dir, { recursive: true });
              fs.writeFileSync(p, content, 'utf8');
              core.info(`Wrote ${p}`);
              files.push(p);
            }
            if (files.length === 0) {
              core.setFailed("No ```file=...``` blocks found in the comment");
            }
            core.setOutput('files', JSON.stringify(files));

      - name: Verify parsed files
        run: |
          echo "Files: ${{ steps.parse.outputs.files }}"
          git status --porcelain

      - name: Create branch, commit, push
        id: commit
        env:
          BR: agent/${{ github.run_id }}
        run: |
          git config user.name "repo-agent[bot]"
          git config user.email "repo-agent[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          git add -A
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Agent apply: $BR"
          git push -u origin "$BR"
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Open Pull Request
        if: steps.commit.outputs.changed == 'true'
        id: pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const head = `agent/${{ github.run_id }}`;
            const base = context.payload.repository.default_branch; // целевая ветка = дефолтная
            const {owner, repo} = context.repo;
            const res = await github.rest.pulls.create({
              owner, repo, head, base,
              title: "Agent: apply changes",
              body: "Автосоздано из комментария с `/apply`."
            });
            core.setOutput("number", res.data.number);
            core.info(`PR #${res.data.number} created`);

      - name: Enable auto-merge (optional)
        if: steps.commit.outputs.changed == 'true'
        continue-on-error: true
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.number }}
          merge-method: squash
