name: Agent – apply file blocks from issue comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse file blocks from comment
        id: parse
        env:
          BODY: ${{ github.event.comment.body }}
        run: |
          mkdir -p .agent
          python3 - << 'PY'
import os, re, json
body = os.environ["BODY"]
blocks = re.findall(r"```file=([^\n]+)\n([\s\S]*?)```", body)
files = []
for path, content in blocks:
    path = path.strip()
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    files.append(path)
open(".agent/files.json","w").write(json.dumps(files))
PY

      - name: Detect changes
        run: |
          if [ ! -f .agent/files.json ]; then
            echo "No file blocks found."; exit 1
          fi
          git status --porcelain

      - name: Create branch, commit, push
        env:
          BR: agent/${{ github.run_id }}
        run: |
          git config user.name "repo-agent[bot]"
          git config user.email "repo-agent[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          git add -A
          git commit -m "Agent apply: $BR"
          git push -u origin "$BR"

      - name: Open Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const br = `agent/${{ github.run_id }}`;
            const {owner, repo} = context.repo;
            const res = await github.rest.pulls.create({
              owner, repo,
              head: br,
              base: "main",
              title: "Agent: apply changes",
              body: "Автосоздано из комментария с `/apply`."
            });
            core.info(`PR #${res.data.number} created`);
