name: AI Apply Patch

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract diff block
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = (context.payload.comment.body || '').trim();
            const fence = body.match(/```(?:diff|patch)?\s*([\s\S]*?)```/i);
            let diffText = '';
            if (fence && fence[1]) diffText = fence[1].trim();
            else {
              const i = body.indexOf('diff --git');
              if (i !== -1) diffText = body.slice(i).trim();
            }
            if (!diffText) core.setFailed('Не найден патч. Вставь блок ```diff ...``` или начни с "diff --git".');
            fs.writeFileSync('ai_patch.diff', diffText + '\n');

      - name: Determine base branch
        id: base
        run: echo "base=${GITHUB_REF_NAME:-${{ github.event.repository.default_branch }}}" >> $GITHUB_OUTPUT

      - name: Create patch branch from base
        env:
          BASE: ${{ steps.base.outputs.base || github.event.repository.default_branch }}
        run: |
          git config user.name "ai-patch-bot"
          git config user.email "ai-patch-bot@users.noreply.github.com"
          git checkout "$BASE"
          git pull --ff-only origin "$BASE"
          git checkout -b "ai/patch-${{ github.run_id }}" "$BASE"

      - name: Apply patch
        run: |
          git apply --whitespace=fix ai_patch.diff
          git add -A
          git commit -m "AI patch ${{ github.run_id }}"

      - name: Push branch
        run: git push -u origin "ai/patch-${{ github.run_id }}"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "ai/patch-${{ github.run_id }}"
          base: ${{ github.event.repository.default_branch }}
          title: "AI patch ${{ github.run_id }}"
          body: |
            PR создан автоматически из комментария с командой /apply.
            Источник: ${{ github.event.comment.html_url }}
