name: AI Apply Patch

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: contains(github.event.comment.body, '/apply')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract diff block from comment
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body || '';
            const m = body.match(/```diff\s*([\s\S]*?)```/i);
            if (!m) {
              core.setFailed('Не найден блок ```diff ... ``` в комментарии.');
            } else {
              require('fs').writeFileSync('ai_patch.diff', m[1].trim() + '\n');
            }

      - name: Create branch
        run: |
          git config user.name "ai-patch-bot"
          git config user.email "ai-patch-bot@users.noreply.github.com"
          git checkout -b "ai/patch-${{ github.run_id }}"

      - name: Apply patch
        run: |
          git apply --whitespace=fix ai_patch.diff
          git add -A
          git commit -m "AI patch ${{ github.run_id }}"

      - name: Push branch
        run: git push origin "ai/patch-${{ github.run_id }}"

      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "ai/patch-${{ github.run_id }}"
          title: "AI patch ${{ github.run_id }}"
          body: |
            PR создан автоматически из комментария с командой /apply.
            Источник: ${{ github.event.comment.html_url }}
